sonar.projectKey=student_panel
sonar.projectName=Student Panel Flutter
sonar.projectVersion=1.0

# 📁 Código y tests
sonar.sources=lib
sonar.tests=test

# 🎯 SOLO analizar tu lógica
sonar.inclusions=lib/usuarios/logica/**

# 🚫 Exclusiones (opcional, puedes dejarlo)
sonar.exclusions=\
  lib/generated/**,\
  lib/**/*.g.dart,\
  lib/**/*.freezed.dart,\
  lib/firebase_options.dart

# 📊 Coverage
sonar.dart.coverage.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8